version: '3.8'

services:
    nodeserver:
        build: 
            context: node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
        networks:        
            - node_network
        volumes:
            - ./node:/usr/src/app
            - /usr/src/app/node_modules   
        tty: true
        ports:
            - "3000:3000"
        depends_on: 
            - db

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - node_network
    
    nginx:
        restart: always
        build:
            context: nginx
        ports:
            - "8080:80"
        networks:
            - node_network

networks: 
    node_network:
        driver: bridge